services:
  mysql:
    image: mysql:8.0
    container_name: global_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: matheus
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"